name: cnm-bert
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.2.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  - pip:
      - transformers==4.38.2
      - tokenizers==0.15.2
      - datasets==2.16.1
      - accelerate==0.26.1
      - jieba==0.42.1
      - numpy==1.26.4
      - tqdm==4.66.1
      - requests==2.31.0
      - wandb==0.16.3
      - tensorboard==2.15.2
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - matplotlib==3.8.3
      - seaborn==0.13.2
      - pandas==2.2.0
      - pytest==8.0.2
      - pytest-cov==4.1.0
      - black==24.2.0
      - ruff==0.2.2
      - mypy==1.8.0
      - jupyter==1.0.0
      - ipython==8.21.0
      - pyyaml
      - wikiextractor
